name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    paths-ignore:
      - '.github/workflows/go.yml'
    branches: [ "main" ]

jobs:

  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ^1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -race -cover ./... -covermode=atomic -coverprofile coverage.out

    - name: Upload coverage file
      uses: codecov/codecov-action@v3
